# https://adventofcode.com/2023/day/3

In [3]:
s = raw"""...............776..............552........968..................589...26...........484..............958......186....546.........484.........
.........*.........778....................*....124...................................*...............*........%..26.........................
......194..380....@....900..........639....467........478*..............582...........798.............326...........894.........#...........
904...........*2.......#......259.....*..........801......464................597.569.............794+................$..218....502..........
...*.....................-...$.....%..431.........*...810.....840+.668..........*.......144=.............................../...........%627.
...890...497.........829.643....504..........465..502..............*........488...................787.184...601....215........-450..........
.......................*............684.....*.............466...970....646..%...........399...........*.............=....88...........=415..
....................139........415...+......854.....683....*.........+.=.......107.676.....*451......83..416....856.....%....765............
..............163..............*...................*......796.....992.............*...............................#.798.....*......819......
.../....678..*...........429..351..........937......629.................*59.677..........652$.292....................*..431..184..*......688
.79......*...694.......-...........492.247......26.......399/.=....................113.........*...................789....*.......469.......
.......94............667.............*..*...933...*684........861...687...567*927.*.....869..509.......................423..................
.596............................561.271.349....-.........139.........@............278......*............@...942*....36......................
.....475...........*268.........*...................695.................850..#.........233.876......@..768......425......85*734.......*349..
.......*..119.96........287.....177.............940*......................*..445.........@.........577..........................39..30......
.....26......*.......................1=.685..........3...120..81.......533...................................718................*...........
.....................306.........335.................*......+...*..................563..240..................*.......349*708...244...319....
..........30..197...........639......................7.../.....471.......-.......@..*..%........895*680.....635.......................*.....
.....*116...*..*..............*...........445.............643.........75.29.....42.586..........................41.....@.....323.....860....
.511.......105.71.......765...670.....489*.........426.........758.....................139............94.793......*....63.....*.............
...*.....................$..................470......*..........*.....69.......590.730*...........553...........814..........604............
.680..............................443..............598...-.....318.....=........*........845..215..*.............................-..........
............237.......180...........#.691...276...........909...............$..527...881.*.....*...585....224....762.....389..193...........
.....@.....=.........@....789.................*.......857........&.450...716.............149..885............*............*............504..
993...906................*.....685..688........385...*........925..*................................700*...811..=......295.....$311.....-...
...@.................956..809.......*..............................577....965.......%846.....$...@.............839..........................
.........704.393%....*............1..562..............716.................$..................387.645........................571.342./.......
......@..*.........226...........*.........526*914...*......172....-..........32............................211.......990......*....695.....
.....272..481.................288.....................370.....*.....740...........281..............430..13..$...............................
397............#............................65................677....................*.586..758....*......*.................49.#973....409..
.............818.........103...........524.*.........150...........781...236.../891.....*.........456.416.591.691-...849....+...........&...
..................457@......*...........&..813...979*.....453*181....*.....-..........286.....565.....................&.......624...........
......#....................221..464..................................604.....978.........................................%412.*.............
619%..176.........=...280......*......*......................493...............*.......................570+....................961..233@....
..............52..50....*.....26......518.207....%.465.........*.............871...817.............384........792.....@754..................
............3*.......703............%..........554..............20.........................879.......-....646*...............415...814......
........944......946..............766.477.492......835......806...........214.........*......*..............................*......%....633.
....266*......*.....-........................#.783*........*..................900.....852....271..+567.452..249..........850................
...........938.661....770...87.841..................@......739../.....230.....*...916....................*..*...636..49.........18..*20..4..
....110................*......*......#341.-.......*.75..........660..........117.....$.803@.780........172.......*....*.160/.....+..........
....+..................92.693.............952..988..................670.....................@...972...........760..194...............24.....
........479*...880..=........&..475&..677..........%283.....642....*............359...154................755.............690...........&....
...../.........*.....590..=..........&.......&....................765......./...*....................419........214-.......*...324..........
......934...470...........10.......*....-....412............750...........496..651...+701...........*....................698......*217......
............................./228...484.854...........627....%......795.......................*.............450...66........................
............978$...274.......................822.........*.....-760............700.........235.346................*.............+.....885...
...................%...582..........338.@.....*...274..252.....................*...720....................700.18.41...........503.......+...
........4..960....................../....722..897.&..........987..........510..104....+..416.....549.......*...*...................407......
.......*......*211............=725...................$574.......*.........................+......*.......788..350...432..............*......
.244...921.........601....36*..................222..............918...344..733.....109.........610....66..............*...............937...
...*.........464...*.../.....991................*....................+....*....285*......538..........*.......914......526...465.722........
............*.....362.460........49............66.121...=...............373.............=.........530..337....=.................*........606
154...713...611............$725....................*..29...425..74..............920.................@.................389...........715.....
......*........../.....143.......................652.........*..*..711...69.26........406.....................37*175........122.....#.......
.....588........39....*......224.........*................868..800...&../...*....407.......46..387.728......................*...............
............-........39.........*.541.595.516...............................484.*.................*...........206.........636..807..........
.............858.............716....*..........810*290..372........@949.........921...................428........*..+..........*............
........486........301*307.........135.................*................264.178......838.....224..-......*......499..816.......227..........
.......*........................................802...608............24*.......*.........940......98....960............................685..
.......425.76.........+94..556...........699.......*.......................%....857.266.*.....................8................624*....=....
............*.................*735......&....$..345....361%.803..856....732.........*....520....*..............%.......269...=.....286......
...........73.901.../..............384.....520......#.........-./...........447......930......279.......634.............#..207.754......473.
..............@...538.936*484.....*....665...........630...............236...@.....%.....................*...985..406............-..........
..............................328..531...%.616...........................*........64..497..105........844.....*......*......207.............
.....*730......................*.......................478..701........+..567........*...........110.......175.......6.737.......+....192...
..363......119....6....942......892....171..358.981..........*........731.........455....#..........*993.......383......*.........505..@....
..............*....%.%....*............*......*..../..%.....................995........850...264..........82%.....=......735.../............
..207...413/.349.@...628.685.........930......231....921.......................................$..142...........-............713....260.....
.................384.........527..........373.............@946....&...............948...949......*......349...838......................*....
.......................210....*.....................*241.........333.......................*..723........*..........632....916-...164..63...
....789....../..859......@....770............286.881.................867.........218......346.........691..368......*.......................
......$...411.....@.781............857................*912.135.&27...........885....*.942.........%............436..264.449.577..92#........
...............9....................*..............391.....*................*......54..=.........108.......................*................
..............$..106........767..290...751................977............990................499...................466.........545...........
...............................=..........*..................................345............./....=.../...266.847....*605....*....219.......
..................984.....735..........761......727.........814.481.....737...*......936...........76.599.*....=...........247...=..........
.....................*697...*.595.................=...........*........*.......480.........................822.....287..................941.
.....182*875...477#..............*...108...................390.......266...........678.593.......-..............$....&.649...../..../...*...
....................279..............*...136........@..........................513.=...*.........332...510.....337............534..236..101.
.......................*538........453......=.......390....235...................*......741............*.................792@...............
..492......639.650.........................................@.....................21........./.......170............................+..@.....
...*..942..=................794.........@..........456............185.395....437...........721..........206..+231...............638...424...
479......*....................*.........251....243*....387........=..................520.............$...../................................
..........971.................995.........................................116.......-.....*950...*....731.....543.......+..............748..
......522................852=..............380..848......932........482......*644......514........40.........#..........869........710..-...
.........*......................#955......./...*....../.....*46.......*.160#.................652..................218..........478*.........
.........870...254.........309.......106......214....840..#.........29.......%........111.....$.........20*865..........&.............694...
..................*316........*323......*................734.881.......33...84.97$..4*..........*135...............772.993............*.....
.......................208...............793.....157............*597....*....................818.........-...260.....*........933....384....
..........106......34......358*263.................+...457*...$.......866.583....................439=..677......@................=..........
......-...*........#.......................................87.68...............#.......186%..................&.....=626.....................
...191...136..453*.............#../537...............%.612........89..417......50.........................429..................859..........
..................432....*89.20...................387..../....../.......*.........121...108...................................&.............
...........768........................134...793................339....206.........*......$.......394.......@.........974..........132*863...
......./...*................252.355.....#......................................335...169...332...*.......896....894..*......................
....629....191..........369*.................109.............326..312*....&...........*.....*....478...........*......432...&......104......
670............................&....967*........*.....................516..92..855...685.712..............936...............88....$.........
.....583......974....26*24......782.....806...160...............669...............@..........606*........%......89..........................
786.............*................................................&..................=............742...........+...................%........
......#....@.939......375..............332-..........575...546*........*....196.628.581....@...............288.........645...467.246..125...
....46...872.....414.....*..=......+........677................342..883.301..*...@.........699.261...796......*....809....-..*.......*......
................$.....828....940..400.........$.40............................39.........*..............=.......-....*........780....925....
.....*375.................39.............418....*................................../..279.367../676..........982.....216....=...............
..703......$....../............703*.......*..904.....465.........*182..92.........173...............610...65................685.....55$.....
.........904...650.................274...6.....................&.........*635...............787.306*.......*.............*..................
..136........................................933......783.724.320...344..................../...........+....51...108..597.41.....809........
...+........715.663............$.....821.....*...........*............*.....@657..354..411..........811..........*..........................
......633.....*............*...925.........991...852........=...=......184..........*.........589.................788...191.................
.........*....574........368.....................@.......373..657.701........411..575.954&......*.......$.....748.........*....758..........
........787........770.............................879............*......88....*..............119.....817.....*.........914....*......751...
.14.173...............*........................189*................509..%......29.............................87................683..*......
...*........../.....563..270*876...123................................................../64.....216........................977......316.....
.......612..516.50...................*................762..23/.........26.........608.............$..466*214.......455...#..#..352......928.
........*.........*......296..@.......970..513.........*.........584..................233.....945................./.....846...+.............
......918.......640..585.....600..550.....*.......=....723.......*.............-.......-..418.....15.180...969.......................703....
...@.......-63...........=........*.......839...769............76........671...268........+..........*.........965....#.....#.568...*.......
.194.....................453......530...................*675......487.=....+.........309....224..507.209.........@.138....300..*..$.........
.......@..@....846.............%.........714...468...150......88......510..............*...*.......*...........................9.816........
.....234.140....*..............903..789.....*.*..............*..............631........702.80....33.........513........276..................
.............381.......................*.803...474......267...296.436.......*........................679....*............*........939...784.
.....-..........................33&.158....................*......*.......569........487...871/............510......274.542.........*.......
......883.....*163...782..-.............379.764@.....912=..796...91.....................&.......979....907.....*......*........167....+.+873
...........110........*..577........&....*............................*778...................$............@.241.428..949...680*.....513.....
....................924........471.470.268..486......../....#......567...........470..469.794....%...............................+..........
..725*532......$........@.......*..........*........926......213............405.....*...*......355...615...#....73........151.....896.......
............980......969....812..28.936.....882..............................&...107.....377...........*.611.......+.......&..737...........
....$594...................*............156.....210....585...........234.821.........................403........837..........*....652.......
...........................247.@881..7.....*....*.....................*.....*.......*........140.351..........................510....*......
...........790*776...................*...270...778......707.110.....487..486...460.70........*.....#...585.702..430..141...........34.......
...52.......................&216..788......................*...................*............199...........*....=......................989...
....$..445...498.254.508*.............*860..711.48......./.............596....305.....618..........337.............198....287...............
.........#....*....@.....352....*..645......*.............328......50.*..................=...-........*584..........*..........*275..986*527
.............560..............815.........931......400............*...592......824.........807...591*................311.....82.............
.........%.......678.926........................19...*......545..649...........*...............*.....393....=896............................
......834...........*............................/....386.....*......=290...772.............545.969...................679.820......704......
..........122...........202....693.................*..............................555*826..............458......691......*.........*........
....#.......&..%692........+......#..333............41...............=204..................868............/.164..................316........
...346..................+.......$...*......396..315....119..@755...............942..918........................*........631.651.............
.................=....836......402.755............=.......*.......*....181.62...*.....%........................596......*............#591...
...............764.....................................488.....880.209........416..................183...156..........917..................."""
input = split(s, '\n')

140-element Vector{SubString{String}}:
 "...............776............." ⋯ 78 bytes ⋯ "186....546.........484........."
 ".........*.........778........." ⋯ 78 bytes ⋯ ".%..26........................."
 "......194..380....@....900....." ⋯ 78 bytes ⋯ ".......894.........#..........."
 "904...........*2.......#......2" ⋯ 78 bytes ⋯ "........\$..218....502.........."
 "...*.....................-...\$." ⋯ 78 bytes ⋯ "............../...........%627."
 "...890...497.........829.643..." ⋯ 78 bytes ⋯ "01....215........-450.........."
 ".......................*......." ⋯ 78 bytes ⋯ ".......=....88...........=415.."
 "....................139........" ⋯ 78 bytes ⋯ "...856.....%....765............"
 "..............163.............." ⋯ 78 bytes ⋯ ".....#.798.....*......819......"
 ".../....678..*...........429..3" ⋯ 78 bytes ⋯ "........*..431..184..*......688"
 ".79......*...694.......-......." ⋯ 78 bytes ⋯ "......789....*.......469......."
 ".......94............667......." ⋯ 78 bytes ⋯ "........

## Part 1

In [20]:
findall(r"\D\d+\D", input[1])

10-element Vector{UnitRange{Int64}}:
 15:19
 32:36
 43:47
 64:68
 70:73
 83:87
 100:104
 109:113
 116:120
 128:132

In [22]:
findall(r"\D\d+\D", "...123...453...")

2-element Vector{UnitRange{Int64}}:
 3:7
 9:13

In [23]:
findall(r"\D\d+\D", "11...123...453...")

2-element Vector{UnitRange{Int64}}:
 5:9
 11:15

In [33]:
findall(r"(\D|^)\d+(\D|$)", "11...123...453...987")

4-element Vector{UnitRange{Int64}}:
 1:3
 5:9
 11:15
 17:20

In [105]:
c = collect(eachmatch(r"(\D|^)(\d+)(\D|$)", "11...123...453...987"))
m = c[1]
m.offsets, m.captures[2]

([1, 1, 3], "11")

In [88]:
"11...123...453...987"[6:8]

"123"

In [106]:
digreg = r"(\D|^)(\d+)(\D|$)"

r"(\D|^)(\d+)(\D|$)"

In [139]:
symbol_map = zeros(Int, length(input[1]), length(input))
for i in 1:length(input[1])
    for j in 1:length(input)
        symbol_map[i,j] = !(isdigit(input[j][i]) || input[j][i] == '.')
    end
end
symbol_map

140×140 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  1  0  0  0  0  0  1  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  1  0  0     0  0  0  1  0  1  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0   

In [140]:
for i in symbol_map[:,2]
    print(i)
end

00000000010000000000000000000000000000000010000000000000000000000000000000000000000001000000000000000100000000100000000000000000000000000000

In [141]:
input[2][10], symbol_map[10, 2]

('*', 1)

In [157]:
example_input = raw"""467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598.."""
input = split(example_input, '\n')

symbol_map = zeros(Int, length(input[1]), length(input))
for i in 1:length(input[1])
    for j in 1:length(input)
        symbol_map[i,j] = !(isdigit(input[j][i]) || input[j][i] == '.')
    end
end
symbol_map

10×10 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  1  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  1  0
 0  0  0  1  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [168]:
partsum = 0

for j in 1:length(input)
    line = input[j]
    for digmatch in eachmatch(digreg, line, overlap=true)
        
        #ledge = digmatch.start > 1 ? (digmatch.start - 1) : 1
        #redge = digmatch.stop == length(line) ? digmatch.stop : (digmatch.stop + 1)
        partnum = parse(Int, digmatch.captures[2])
        
        ledge = digmatch.offsets[1]
        redge = digmatch.offsets[3]
        if redge > length(line)
            redge = length(line)
        end
        
        adj = (symbol_map[ledge, j] != 0) || (symbol_map[redge, j] != 0)
        if (!adj) && (j > 1)
            # check the top
            for i in ledge:redge
                if symbol_map[i, j-1] != 0
                    adj = true
                    break
                end
            end
        end
        
        if (!adj) && (j < length(input))
            # check the bottom
            for i in ledge:redge
                if symbol_map[i, j+1] != 0
                    adj = true
                    break
                end
            end
        end
        if adj
            partsum += partnum
        end
    end
end

partsum

4361

In [169]:
input = split(s, '\n')

symbol_map = zeros(Int, length(input[1]), length(input))
for i in 1:length(input[1])
    for j in 1:length(input)
        symbol_map[i,j] = !(isdigit(input[j][i]) || input[j][i] == '.')
    end
end

partsum = 0

for j in 1:length(input)
    line = input[j]
    for digmatch in eachmatch(digreg, line, overlap=true)
        
        #ledge = digmatch.start > 1 ? (digmatch.start - 1) : 1
        #redge = digmatch.stop == length(line) ? digmatch.stop : (digmatch.stop + 1)
        partnum = parse(Int, digmatch.captures[2])
        
        ledge = digmatch.offsets[1]
        redge = digmatch.offsets[3]
        if redge > length(line)
            redge = length(line)
        end
        
        adj = (symbol_map[ledge, j] != 0) || (symbol_map[redge, j] != 0)
        if (!adj) && (j > 1)
            # check the top
            for i in ledge:redge
                if symbol_map[i, j-1] != 0
                    adj = true
                    break
                end
            end
        end
        
        if (!adj) && (j < length(input))
            # check the bottom
            for i in ledge:redge
                if symbol_map[i, j+1] != 0
                    adj = true
                    break
                end
            end
        end
        if adj
            partsum += partnum
        end
    end
end

partsum

539637

## Part 2

In [222]:
input = split(example_input, '\n')

10-element Vector{SubString{String}}:
 "467..114.."
 "...*......"
 "..35..633."
 "......#..."
 "617*......"
 ".....+.58."
 "..592....."
 "......755."
 "...\$.*...."
 ".664.598.."

In [223]:
gear_map = zeros(Int, length(input[1]), length(input))
for i in 1:length(input[1])
    for j in 1:length(input)
        gear_map[i,j] = input[j][i] == '*'
    end
end
gear_map

10×10 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  1  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [224]:
first_adj = zero(gear_map)
second_adj = zero(gear_map)
extra_adj = zero(gear_map)

for j in 1:length(input)
    line = input[j]
    for digmatch in eachmatch(digreg, line, overlap=true)
        
        partnum = parse(Int, digmatch.captures[2])
        
        ledge = digmatch.offsets[1]
        redge = digmatch.offsets[3]
        if redge > length(line)
            redge = length(line)
        end

        gears = []
        
        if gear_map[ledge, j] != 0
            push!(gears, (ledge, j))
        end
        
        if gear_map[redge, j] != 0
            push!(gears, (redge, j))
        end
        
        if j > 1
            # check the top
            for i in ledge:redge
                if gear_map[i, j-1] != 0
                    push!(gears, (i, j-1))
                end
            end
        end
        
        if j < length(input)
            # check the bottom
            for i in ledge:redge
                if gear_map[i, j+1] != 0
                    push!(gears, (i, j+1))
                end
            end
        end
        #println("partnum", partnum, " has gears ", gears)
        for gear in gears
            i, j = gear
            if first_adj[i, j] == 0
                first_adj[i, j] = partnum
            else
                if second_adj[i, j] == 0
                    second_adj[i, j] = partnum
                else
                    if extra_adj[i, j] == 0
                        extra_adj[i, j] = partnum
                    end
                end
            end
        end
    end
end

gnotratiosum = 0
for i in 1:size(gear_map)[1]
    for j in 1:size(gear_map)[2]
        if (second_adj[i, j] != 0) && (extra_adj[i, j] == 0)
            gnotratio = first_adj[i, j] * second_adj[i, j]
            gnotratiosum += gnotratio
        end
    end
end
gnotratiosum

467835

In [225]:
input = split(s, '\n')

gear_map = zeros(Int, length(input[1]), length(input))
for i in 1:length(input[1])
    for j in 1:length(input)
        gear_map[i,j] = input[j][i] == '*'
    end
end
gear_map

140×140 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0   

In [248]:
first_adj = zero(gear_map)
second_adj = zero(gear_map)
extra_adj = zero(gear_map)

for j in 1:length(input)
    line = input[j]
    for digmatch in eachmatch(digreg, line, overlap=true)
        
        partnum = parse(Int, digmatch.captures[2])
        
        ledge = digmatch.offsets[1]
        redge = digmatch.offsets[3]
        if redge > length(line)
            redge = length(line)
        end

        gears = []
        
        if gear_map[ledge, j] != 0
            push!(gears, (ledge, j))
        end
        
        if gear_map[redge, j] != 0
            push!(gears, (redge, j))
        end
        
        if j > 1
            # check the top
            for i in ledge:redge
                if gear_map[i, j-1] != 0
                    push!(gears, (i, j-1))
                end
            end
        end
        
        if j < length(input)
            # check the bottom
            for i in ledge:redge
                if gear_map[i, j+1] != 0
                    push!(gears, (i, j+1))
                end
            end
        end
        #if partnum == 930
        #    println("partnum", partnum, " has gears ", gears, "j=",j)
        #end
        for gear in gears
            ig, jg = gear
            if first_adj[ig, jg] == 0
                first_adj[ig, jg] = partnum
            else
                if second_adj[ig, jg] == 0
                    second_adj[ig, jg] = partnum
                else
                    if extra_adj[ig, jg] == 0
                        extra_adj[ig, jg] = partnum
                    end
                end
            end
        end
    end
end

gnotratiosum = 0
for i in 1:size(gear_map)[1]
    for j in 1:size(gear_map)[2]
        if (second_adj[i, j] != 0) && (extra_adj[i, j] == 0)
            gnotratio = first_adj[i, j] * second_adj[i, j]
            #println("included", i, ",",j,'=',first_adj[i, j],",",second_adj[i, j])
            gnotratiosum += gnotratio
        end
    end
end
gnotratiosum

82818007