In [1]:
Π

LoadError: UndefVarError: `Π` not defined

In [2]:
?α

"α" can be typed by \alpha<tab>

search:

Couldn't find α
Perhaps you meant !, %, &, ', *, +, -, /, :, <, >, \, ^, |, ~, ÷, π, ℯ, ∈ or ∉


No documentation found.

Binding `α` does not exist.


In [5]:
π

π = 3.1415926535897...

In [7]:
2π + 3

9.283185307179586

In [8]:
v = [1.2,3,1]

3-element Vector{Float64}:
 1.2
 3.0
 1.0

In [9]:
v=[1,4,2]

3-element Vector{Int64}:
 1
 4
 2

In [10]:
12/0

Inf

In [11]:
12.2/0

Inf

In [15]:
typeof(4/3)

Float64

In [14]:
typeof(4//3)

Rational{Int64}

In [30]:
5 ÷ 3

1

In [29]:
?÷

"÷" can be typed by \div<tab>

search: ÷



```
div(x, y)
÷(x, y)
```

The quotient from Euclidean (integer) division. Generally equivalent to a mathematical operation x/y without a fractional part.

See also: [`cld`](@ref), [`fld`](@ref), [`rem`](@ref), [`divrem`](@ref).

# Examples

```jldoctest
julia> 9 ÷ 4
2

julia> -5 ÷ 3
-1

julia> 5.0 ÷ 2
2.0

julia> div.(-5:5, 3)'
1×11 adjoint(::Vector{Int64}) with eltype Int64:
 -1  -1  -1  0  0  0  0  0  1  1  1
```

---

```
div(x, y, r::RoundingMode=RoundToZero)
```

The quotient from Euclidean (integer) division. Computes `x / y`, rounded to an integer according to the rounding mode `r`. In other words, the quantity

```
round(x / y, r)
```

without any intermediate rounding.

!!! compat "Julia 1.4"
    The three-argument method taking a `RoundingMode` requires Julia 1.4 or later.


See also [`fld`](@ref) and [`cld`](@ref), which are special cases of this function.

!!! compat "Julia 1.9"
    `RoundFromZero` requires at least Julia 1.9.


# Examples:

```jldoctest
julia> div(4, 3, RoundDown) # Matches fld(4, 3)
1
julia> div(4, 3, RoundUp) # Matches cld(4, 3)
2
julia> div(5, 2, RoundNearest)
2
julia> div(5, 2, RoundNearestTiesAway)
3
julia> div(-5, 2, RoundNearest)
-2
julia> div(-5, 2, RoundNearestTiesAway)
-3
julia> div(-5, 2, RoundNearestTiesUp)
-2
julia> div(4, 3, RoundFromZero)
2
julia> div(-4, 3, RoundFromZero)
-2
```


In [21]:
typeof(1.321f25*2)

Float32

In [25]:
zero([1,2,.41])

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [31]:
[1,2,3]^3

LoadError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)

Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer)
   @ Base strings/basic.jl:733
  ^(::Rational, ::Integer)
   @ Base rational.jl:491
  ^(::LinearAlgebra.UniformScaling, ::Number)
   @ LinearAlgebra /usr/share/julia/stdlib/v1.9/LinearAlgebra/src/uniformscaling.jl:317
  ...


In [32]:
[1,2,3].^3

3-element Vector{Int64}:
  1
  8
 27

In [41]:
atan(1,2)

0.4636476090008061

In [40]:
atand(1,2)

26.56505117707799

In [42]:
'\u2200'

'∀': Unicode U+2200 (category Sm: Symbol, math)

In [44]:
s = "hello world"

"hello world"

In [45]:
s[2]

'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [50]:
s[end-1]

'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)

In [52]:
s[1]

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

In [53]:
s[begin]

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

In [54]:
l = [1,2,3]
l[0]

LoadError: BoundsError: attempt to access 3-element Vector{Int64} at index [0]

In [55]:
l[1]

1

In [60]:
s[1:4]

"hell"

In [61]:
s[1:end-5]

"hello "

In [62]:
typeof(s)

String

In [63]:
typeof(s[2:5])

String

In [64]:
typeof(@views s[2:5])

SubString{String}

In [67]:
split("a,b,c", ",")

3-element Vector{SubString{String}}:
 "a"
 "b"
 "c"

In [74]:
i = 0

0

In [75]:
while i <= 3
    println(i)
    i += 1
end

0
1
2
3


In [81]:
sqrt(-1+0im)

0.0 + 1.0im