In [2]:
import re
import numpy as np

import collections
from scipy import ndimage

https://adventofcode.com/2020

# Day 9

In [10]:
with open('input9') as f:
    input9 = f.read().strip()

## Part 1

In [44]:
test_input = """35
20
15
25
47
40
62
55
65
95
102
117
150
182
127
219
299
277
309
576"""
def parse_input(inpt):
    return np.array(inpt.split('\n'), dtype=int)
parse_input(test_input)

array([ 35,  20,  15,  25,  47,  40,  62,  55,  65,  95, 102, 117, 150,
       182, 127, 219, 299, 277, 309, 576])

In [60]:
def get_different_combinations(arr):
    c1, c2 = np.meshgrid(arr, arr)
    same_comb_msk = ~np.eye(arr.size, dtype=bool)
    return np.array((c1[same_comb_msk], c2[same_comb_msk]))

def validate_xmas(arr, preamble_size):    
    valid = -np.ones(len(arr), dtype=int)  # -1 means not checked
    for i in list(range(len(arr)))[preamble_size:]:
        preamble = arr[(i-preamble_size):i]
        assert len(preamble)==preamble_size
        
        combs = get_different_combinations(preamble)
        sums = np.sum(combs, axis=0)
        valid[i] = np.in1d(arr[i], sums)[0]
        
    return valid
        
inarr = parse_input(test_input)
assert inarr[validate_xmas(inarr, 5)==0][0] == 127

In [64]:
arr9 = parse_input(input9)
validity9 = validate_xmas(arr9, 25)
validity9

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [92]:
invalid_numbers = arr9[validity9==0]
assert len(invalid_numbers) == 1
invalid_number9 = invalid_numbers[0]
invalid_number9

375054920

## Part 2 

In [71]:
arr9.size**2

1000000

So nested for loop probably won't be prohibitively long?

In [90]:
def find_contiguous_xmas_sum(arr, invalid_number):
    match = None
    for i in range(len(arr)):
        if match is not None:
            break
        for j in range(i+2, len(arr)):
            if np.sum(arr[i:j]) == invalid_number:
                match = (i, j)
                break
    return match

testarr = parse_input(test_input)
i, j = find_contiguous_xmas_sum(testarr, 127)

np.min(testarr[i:j]) + np.max(testarr[i:j])

62

In [95]:
i, j = find_contiguous_xmas_sum(arr9, invalid_number9)
np.min(arr9[i:j]) + np.max(arr9[i:j])

54142584

# Day 10

In [5]:
input10 = np.loadtxt('input10', dtype=int)

array([  8, 131,  91,  35,  47, 116, 105, 121,  56,  62,  94,  72,  13,
        82, 156, 102,  12,  59,  31, 138,  46, 120,   7, 127, 126, 111,
         2, 123,  22,  69,  18, 157,  75, 149,  88,  81,  23,  98, 132,
         1,  63, 142,  37, 133,  61, 112, 122, 128, 155, 145, 139,  66,
        42, 134,  24,  60,   9,  28,  17,  29, 101, 148,  96,  68,  25,
        19,   6,  67, 113,  55,  40, 135,  97,  79,  48, 159,  14,  43,
        86,  36,  41,  85,  87, 119,  30, 108,  80, 152, 158, 151,  32,
        78, 150,  95,   3,  52,  49])

## Part 1

In [12]:
test_input = np.array("""16
10
15
5
1
11
7
19
6
12
4""".split('\n'), dtype=int)

In [34]:
all_jolts = np.concatenate([test_input, [np.max(test_input+3), 0]])
num, counts = np.unique(np.diff(np.sort(all_jolts)), return_counts=True)
assert dict(zip(num, counts)) == {1: 7, 3:5}

In [36]:
test_input2 = np.array("""28
33
18
42
31
14
46
20
48
47
24
23
49
45
19
38
39
11
1
32
25
35
8
17
7
9
4
2
34
10
3""".split('\n'), dtype=int)

In [39]:
all_jolts = np.concatenate([test_input2, [np.max(test_input2+3), 0]])
num, counts = np.unique(np.diff(np.sort(all_jolts)), return_counts=True)
assert dict(zip(num, counts)) == {1: 22, 3:10}

In [40]:
all_jolts = np.concatenate([input10, [np.max(input10+3), 0]])
num, counts = np.unique(np.diff(np.sort(all_jolts)), return_counts=True)
d = dict(zip(num, counts))
d, d[1]*d[3]

({1: 66, 3: 32}, 2112)

## Part 2 

In [77]:
def count_runs(arr, runnumber=1):
    all_jolts = np.concatenate([arr, [np.max(arr+3), 0]])
    sarr = np.sort(all_jolts)
    dsarr = np.diff(sarr)
    
    #brute-force count the number of 1-runs
    runs = []
    runi = 0
    for e in dsarr:
        if e == 1:
            runi += 1
        elif runi!= 0:
            runs.append(runi)
            runi = 0
        
    return np.array(runs) +1 # the number of times a 1 appears in that run
count_runs(test_input)

array([2, 4, 3, 2])

Now count runs of 1 and multiple bythe number of ways they can be arranged

In [81]:
# find out the largest run we need to map out
np.max(count_runs(test_input)), np.max(count_runs(test_input2)), np.max(count_runs(input10))

(4, 5, 5)

In [84]:
runlength_to_narrangements = {2: 1, 3:2, 4:4, 5:7}
def count_permutations(arr):
    run_counts = count_runs(arr)
    return np.prod([runlength_to_narrangements[count] for count in run_counts])
assert count_permutations(test_input) == 8
assert count_permutations(test_input2) == 19208

In [85]:
count_permutations(input10)

3022415986688

# Day 11

In [2]:
!mv ~/Desktop/input.txt input11

In [3]:
with open('input11') as f:
    input11 = f.read().strip()

## Part 1

In [51]:
test_input = """L.LL.LL.LL
LLLLLLL.LL
L.L.L..L..
LLLL.LL.LL
L.LL.LL.LL
L.LLLLL.LL
..L.L.....
LLLLLLLLLL
L.LLLLLL.L
L.LLLLL.LL"""

def make_seat_map(inptstr, has_seat='L'):
    arr = np.array([list(row) for row in inptstr.split('\n')])
    return arr == has_seat

seat_map = make_seat_map(test_input)
occupied = make_seat_map(test_input, '#')

def seat_string(occupied, has_seat):
    strs = []
    for  orow, hrow in zip(occupied, has_seat):
        rowstr = []
        for o, h in zip(orow, hrow):
            if o:
                rowstr.append('#')
            elif h:
                rowstr.append('L')
            else:
                rowstr.append('.')
        
        strs.append(''.join(rowstr))
        strs.append('\n')
        
    return ''.join(strs[:-1])

print(seat_string(occupied, seat_map))

L.LL.LL.LL
LLLLLLL.LL
L.L.L..L..
LLLL.LL.LL
L.LL.LL.LL
L.LLLLL.LL
..L.L.....
LLLLLLLLLL
L.LLLLLL.L
L.LLLLL.LL


In [53]:
seat_map = make_seat_map(test_input)
occupied = make_seat_map(test_input, '#')

def step(occupied, has_seat):
    kernel = [[1,1,1], [1, 0, 1], [1, 1, 1]]
    n_neighbors = ndimage.correlate(occupied, kernel, mode='constant', cval=0, output=int)
    to_occupy = n_neighbors == 0
    to_vacate = n_neighbors >= 4
    
    occupied = occupied | (to_occupy & has_seat)
    occupied = occupied & ~to_vacate
    
    return occupied

step1 = step(occupied, seat_map)
step2 = step(step1, seat_map)

assert seat_string(step2, seat_map) == """#.LL.L#.##
#LLLLLL.L#
L.L.L..L..
#LLL.LL.L#
#.LL.LL.LL
#.LLLL#.##
..L.L.....
#LLLLLLLL#
#.LLLLLL.L
#.#LLLL.##"""

In [58]:
seat_map = make_seat_map(test_input)
occupied = make_seat_map(test_input, '#')

this_map = occupied
last_map = None
i = 0
while not np.all(last_map == this_map):
    last_map = this_map
    this_map = step(this_map, seat_map)
    i += 1
    
assert i == 6
assert np.sum(this_map) == 37

In [60]:
seat_map = make_seat_map(input11)
occupied = make_seat_map(input11, '#')

this_map = occupied
last_map = None
i = 0
while not np.all(last_map == this_map):
    last_map = this_map
    this_map = step(this_map, seat_map)
    i += 1
    
i, np.sum(this_map)

(81, 2204)

## Part 2 

In [78]:
DIRECTION_VECTORS = np.array([(1,0),(-1,0),(0,1),(0,-1),(1,1),(-1, 1),(1, -1),(-1, -1)])
def find_site_seat(startingx, startingy, seat_map):
    visible_seats = np.zeros(seat_map.shape, dtype=bool)
    for vx, vy in DIRECTION_VECTORS:
        for i in range(1, np.max(seat_map.shape)):
            xi = startingx + i*vx
            yi = startingy + i*vy
            if not (0 <= xi < seat_map.shape[0]) or not (0 <= yi < seat_map.shape[1]):
                break
                
            if seat_map[xi, yi]:
                visible_seats[xi, yi] = True
                break
    return visible_seats

seat_map = make_seat_map(test_input)
occupied = make_seat_map(test_input, '#')
print(seat_string(find_site_seat(5, 5, seat_map), seat_map))

L.LL.LL.LL
LLLLLLL.LL
L.L.L..L..
LLL#.LL.LL
L.LL.##.LL
L.LL#L#.LL
..L.#.....
LLLLL#L#LL
L.LLLLLL.L
L.LLLLL.LL


In [82]:
def construct_visible_map(seat_map):
    visible_map = []
    for i in range(seat_map.shape[0]):
        row = []
        for j in range(seat_map.shape[1]):
            if seat_map[i ,j]:
                row.append(find_site_seat(i, j, seat_map))
            else:
                row.append(np.zeros(seat_map.shape, dtype=bool))
        visible_map.append(row)
    return np.array(visible_map)
assert np.all(construct_visible_map(seat_map)[5, 5] ==  find_site_seat(5, 5, seat_map))

In [94]:
def step2(occupied, seat_map, visible_map=None):
    if visible_map is None:
        visible_map = construct_visible_map(seat_map)
        
    nvisible = np.zeros(seat_map.shape, dtype=int)
    for i in range(seat_map.shape[0]):
        for j in range(seat_map.shape[1]):
            if seat_map[i,j]:
                nvisible[i, j] = np.sum(occupied & visible_map[i, j])
     
    new_occupied = occupied.copy()
    #nvisible now contains the number of people that seat can see
    new_occupied[nvisible >= 5] = False
    new_occupied[(nvisible == 0) & seat_map] = True
    return new_occupied

occupied2 = step2(occupied, seat_map)
occupied3 = step2(occupied2, seat_map)

assert np.all(occupied2 == seat_map)
assert seat_string(occupied3, seat_map) == """#.LL.LL.L#
#LLLLLL.LL
L.L.L..L..
LLLL.LL.LL
L.LL.LL.LL
L.LLLLL.LL
..L.L.....
LLLLLLLLL#
#.LLLLLL.L
#.LLLLL.L#"""


In [99]:
seat_map = make_seat_map(test_input)
occupied = make_seat_map(test_input, '#')

this_map = occupied
last_map = None
i = 0
while not np.all(last_map == this_map):
    last_map = this_map
    this_map = step2(this_map, seat_map)
    i += 1
    
i, np.sum(this_map)

(7, 26)

In [100]:
%timeit step2(this_map, seat_map)

4.56 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [102]:
make_seat_map(test_input).shape,  make_seat_map(input10).shape

((10, 10), (91, 95))

Real thing - might take some time since this is a rather slow approach and above suggestions ~1 sec per iteration.

In [106]:
seat_map = make_seat_map(input11)
occupied = make_seat_map(input11, '#')

this_map = occupied
last_map = None
i = 0
while not np.all(last_map == this_map):
    print(i, end='\r')
    last_map = this_map
    this_map = step2(this_map, seat_map)
    i += 1
    
i, np.sum(this_map)

(86, 1986)

# Day 12

In [2]:
with open('input12') as f:
    input12 = f.read().strip()

## Part 1

In [3]:
test_input="""F10
N3
F7
R90
F11"""
def parse_input(inptstr):
    return [(e[0], int(e[1:])) for e in inptstr.strip().split('\n')]
parse_input(test_input)

[('F', 10), ('N', 3), ('F', 7), ('R', 90), ('F', 11)]

In [15]:
# I'm an astronomer so east and north are positive x and y
# angle is degrees east of north

class Boat:
    def __init__(self, initial_direction=90):
        self.direction = 90
        self.x = self.y = 0
        
    @property
    def manhattan_distance(self):
        return np.abs(self.x) + np.abs(self.y)
    
    def execute_instruction(self, action, number):
        if action == 'N':
            self.y += number
        elif action == 'S':
            self.y -= number
        elif action == 'E':
            self.x += number
        elif action == 'W':
            self.x -= number
        elif action == 'L':
            self.direction -= number
        elif action == 'R':
            self.direction += number
        elif action == 'F':
            self.x += number*np.sin(np.radians(self.direction))
            self.y += number*np.cos(np.radians(self.direction))
        else:
            raise ValueError(f'invalid action {action}')
            
    def execute_instruction_string(self, s, verbose=False):
        for elem in parse_input(s):
            if verbose:
                print(test_boat.x, test_boat.y, test_boat.direction, test_boat.manhattan_distance)
            self.execute_instruction(*elem)
        if verbose:
            print(test_boat.x, test_boat.y, test_boat.direction, test_boat.manhattan_distance)
            
test_boat = Boat()
test_boat.execute_instruction_string(test_input, verbose=True)
assert test_boat.manhattan_distance == 25

0 0 90 0
10.0 6.123233995736766e-16 90 10.0
10.0 3.0000000000000004 90 13.0
17.0 3.000000000000001 90 20.0
17.0 3.000000000000001 180 20.0
17.0 -7.999999999999999 180 25.0


In [17]:
boat = Boat()

boat.execute_instruction_string(input12, verbose=False)
boat.manhattan_distance

1601.000000000001

## Part 2 

In [37]:
class CorrectedBoat(Boat):
    def __init__(self):
        super().__init__()
        # waypoint in units relative to boat
        self.wx = 10
        self.wy = 1
        
    def execute_instruction(self, action, number):
        if action == 'N':
            self.wy += number
        elif action == 'S':
            self.wy -= number
        elif action == 'E':
            self.wx += number
        elif action == 'W':
            self.wx -= number
        elif action == 'L':
            sin = np.sin(np.radians(number))
            cos = np.cos(np.radians(number))
            self.wx, self.wy = (self.wx*cos - self.wy*sin), (self.wx*sin + self.wy*cos)
        elif action == 'R':
            sin = np.sin(np.radians(-number))
            cos = np.cos(np.radians(-number))
            self.wx, self.wy = (self.wx*cos - self.wy*sin), (self.wx*sin + self.wy*cos)
        elif action == 'F':
            self.x += number*self.wx
            self.y += number*self.wy
        else:
            raise ValueError(f'invalid action {action}')
            
    def execute_instruction_string(self, s, verbose=False):
        for elem in parse_input(s):
            if verbose:
                print(test_boat.x, test_boat.y, test_boat.wx, test_boat.wy, test_boat.manhattan_distance)
            self.execute_instruction(*elem)
        if verbose:
            print(test_boat.x, test_boat.y, test_boat.wx, test_boat.wy, test_boat.manhattan_distance)
    
test_boat = CorrectedBoat()
test_boat.execute_instruction_string(test_input, verbose=True)
assert test_boat.manhattan_distance == 286

0 0 10 1 0
100 10 10 1 110
100 10 10 4 110
170 38 10 4 208
170 38 4.000000000000001 -10.0 208
214.0 -72.0 4.000000000000001 -10.0 286.0


In [38]:
boat = CorrectedBoat()

boat.execute_instruction_string(input12, verbose=False)
boat.manhattan_distance

13340.000000000007

# Day 13

In [3]:
with open('input13') as f:
    input13 = f.read().strip()

## Part 1

In [47]:
test_input = """939
7,13,x,x,59,x,31,19"""
def parse_input(s):
    departure, buses = s.split('\n')
    buses = [-1 if b=='x' else int(b) for b in buses.split(',')]
    return int(departure), np.array(buses)
test_departure, test_buses = parse_input(test_input)
test_departure, test_buses

(939, array([ 7, 13, -1, -1, 59, -1, 31, 19]))

In [48]:
def find_buses_after(buses, after):
    dminutes = np.arange(np.max(buses))[:, np.newaxis] # this is the longest a wait can possibly be
    time = dminutes + after
    time_since_departure = time%buses
    when_buses_arrive = np.where(time_since_departure == 0)
    return time[when_buses_arrive[0]].ravel(), buses[when_buses_arrive[1]].ravel()
time, bus = find_buses_after(test_buses[test_buses>0], test_departure)
assert (time[0]-departure) * bus[0] == 295

In [50]:
departure, buses = parse_input(input13)
time, bus = find_buses_after(buses[buses>0], departure)
(time[0]-departure) * bus[0]

2935

## Part 2 

In [82]:
t = 1068781
offsets = np.arange(len(test_buses))
offsets_masked = offsets[test_buses>0]
test_buses_masked = test_buses[test_buses>0]
(t + offsets_masked) % test_buses_masked

# brute force:
def brute_force_buses_contest(buses, verbose=False, startat=0):
    iverbose = int(verbose)
    offsets = np.arange(len(buses))
    offsets_masked = offsets[buses>0]
    buses_masked = buses[buses>0]
    t = startat
    while True:
        if np.all((t + offsets_masked) % buses_masked == 0):
            return t
        t += 1
        if verbose and t%iverbose == 0:
            print(t, end='\r')
%time result = brute_force_buses_contest(test_buses)
assert result == 1068781

CPU times: user 4.73 s, sys: 0 ns, total: 4.73 s
Wall time: 4.73 s


In [83]:
%time brute_force_buses_contest(test_buses, verbose=500000)

CPU times: user 4.92 s, sys: 0 ns, total: 4.92 s
Wall time: 4.91 s


1068781

Now just let it run while I think about a better solution or my kid distracts me from the screen... This is probably a chinese remainder theorem problem, but need to write it out.



In [86]:
departure, buses = parse_input(input13)
%time brute_force_buses_contest(buses, verbose=500000, startat=100000000000000)

KeyboardInterrupt: 

Well that made only a few percent progress in several hours.

Fortunately, turns out it's a standard mod congruence problem, so can use the basic seive algorithm without anything fancy if it's fast enough.

In [94]:
def sieve_buses_contest(buses, verbose=False, startat=0):
    iverbose = int(verbose)
    offsets = np.arange(len(buses))
    offsets_masked = offsets[buses>0]
    buses_masked = buses[buses>0]
    
    # sort into decreasing order of bus number
    sorti = np.argsort(buses_masked)
    offsets_sorted = offsets_masked[sorti][::-1]
    buses_sorted = buses_masked[sorti][::-1]
    
    t = startat
    i = 0
    step_size = 1
    idx = 0
    while True:
        if (t + offsets_sorted[idx]) % buses_sorted[idx] == 0:
            if verbose:
                print('\nFound', idx)
            step_size *= buses_sorted[idx]
            idx += 1
            if idx >= len(buses_sorted):
                return t
            else:
                continue
            
        t += step_size

        i += 1
        if verbose and i%iverbose == 0:
            print(t, i, end='\r')
            
%time result = sieve_buses_contest(test_buses)
assert result == 1068781

CPU times: user 303 µs, sys: 0 ns, total: 303 µs
Wall time: 193 µs


In [97]:
%time sieve_buses_contest(buses)

CPU times: user 874 µs, sys: 0 ns, total: 874 µs
Wall time: 759 µs


836024966345345

Well that is a dramatic speedup...

# Day N

In [2]:
!mv ~/Desktop/input.txt inputN

In [ ]:
with open('inputN') as f:
    inputN = f.read().strip()

## Part 1

## Part 2 